---
# tasks file for jenkins
- name: Download Long Term Jenkins release
  yum_repository:
    name: jenkins
    state: present
    description: Official Jenkins Yum Repo
    baseurl: http://pkg.jenkins.io/redhat
    gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    gpgcheck: yes
    enabled: yes

- name: yum update
  yum:
    name: '*'
    state: latest

- name: Install java
  yum:
    name: java-11-openjdk-devel
    state: present

- name: Install jenkins
  yum:
    name: jenkins
    state: latest

- name: daemon-reload to pick up config changes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: started

