---
# tasks file for ansible
- name: Install epel-release
  yum:
    name: epel-release
    state: installed

- name: yum update
  yum:
    name: '*'
    state: latest

- name: Install ansible
  yum:
    name: ansible
    state: installed